export const TYPE_COLOR_MAP: Record<string, string> = {
  fire: "bg-fire",
  bug: "bg-bug",
  water: "bg-water",
  poison: "bg-poison",
  normal: "bg-normal",
  rock: "bg-rock",
  ground: "bg-ground",
  fighting: "bg-fighting",
  ghost: "bg-ghost",
  psychic: "bg-psychic",
  ice: "bg-ice",
  dragon: "bg-dragon",
  dark: "bg-dark",
  fairy: "bg-fairy",
  electric: "bg-electric",
  steel: "bg-steel",
  grass: "bg-grass",
};

export const TYPE_BG_MAP: Record<string, string> = {
  fire: "bg-bg-fire",
  bug: "bg-bg-bug",
  water: "bg-bg-water",
  flying: "bg-bg-flying",
  poison: "bg-bg-poison",
  normal: "bg-bg-normal",
  rock: "bg-bg-rock",
  ground: "bg-bg-ground",
  fighting: "bg-bg-fighting",
  ghost: "bg-bg-ghost",
  psychic: "bg-bg-psychic",
  ice: "bg-bg-ice",
  dragon: "bg-bg-dragon",
  dark: "bg-bg-dark",
  fairy: "bg-bg-fairy",
  electric: "bg-bg-electric",
  steel: "bg-bg-steel",
  grass: "bg-bg-grass",
};
